// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNxxS7gqswavHYFKppGLCTJdyu5G_4DDc',
    appId: '1:1023376554960:web:4b6db87e6338aa660c97d5',
    messagingSenderId: '1023376554960',
    projectId: 'aquality-80539',
    authDomain: 'aquality-80539.firebaseapp.com',
    storageBucket: 'aquality-80539.firebasestorage.app',
    measurementId: 'G-R4JGQGWBKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_-fJ4lsuftj82blRRdg81EnrluUuPZZo',
    appId: '1:1023376554960:android:cd28fa2a94d7102f0c97d5',
    messagingSenderId: '1023376554960',
    projectId: 'aquality-80539',
    storageBucket: 'aquality-80539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4dg3ZQ6AXqXFkpDv3j97hSFYJgocotn0',
    appId: '1:1023376554960:ios:a993e108481520270c97d5',
    messagingSenderId: '1023376554960',
    projectId: 'aquality-80539',
    storageBucket: 'aquality-80539.firebasestorage.app',
    iosBundleId: 'com.example.aqualityArduinoBasedWaterQualityMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4dg3ZQ6AXqXFkpDv3j97hSFYJgocotn0',
    appId: '1:1023376554960:ios:a993e108481520270c97d5',
    messagingSenderId: '1023376554960',
    projectId: 'aquality-80539',
    storageBucket: 'aquality-80539.firebasestorage.app',
    iosBundleId: 'com.example.aqualityArduinoBasedWaterQualityMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNxxS7gqswavHYFKppGLCTJdyu5G_4DDc',
    appId: '1:1023376554960:web:fa2edf94a99123a90c97d5',
    messagingSenderId: '1023376554960',
    projectId: 'aquality-80539',
    authDomain: 'aquality-80539.firebaseapp.com',
    storageBucket: 'aquality-80539.firebasestorage.app',
    measurementId: 'G-GVL7L7T0R2',
  );
}
